# Generated by Django 3.2.7 on 2021-09-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210916_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
